### ISSUE TITLE
Etiqueta de resultado

### ISSUE THREAD

**Issue by niba291** [training-webFactura/ejercicio_2#4]
Crear la etiqueta para mostrar el resultado de la api

**Comment by EstebanCardenas27** [comment]
###add
-Se realizó la creación del componente Twig y un controlador asignado con los cuales se presenta la vista correspondiente a los resultados seleccionados durante la transacción a modo de detalle general previo a pagar. 

### Controladores
-Nueva función que valida los parámetros necesarios para la emisión y visualización de la información previa a pagar.
        - src/controller/PaymentController.php
 ###Componentes
-Nuevo componente que entrega una vista de los resultados previos para realizar el pago.
          -src/templates/payment/index.html.twig
