### ISSUE TITLE
Realizar nueva clase de simulación api de pago

### ISSUE THREAD

**Issue by niba291** [training-webFactura/ejercicio_2#6]
Creación de modelo de api para devolver un mensaje

[mercado pago, transbank, webpay, kiphu, paypal, redolcomp]

**Comment by EstebanCardenas27** [comment]
## NEW VERSION [1.0.8] - 2024-02-06
### Added
- Se realizaron las clases necesarias para gestionar cada método de pago.
    - 

- *******RepositorioGitHubLink****

- Desarrollador Responsable: Esteban Cárdenas

### Entidades
-No presentaron cambios

### Clases
- Una clase nueva para cada método de pago:
    -khyp.php
    -mercadoPago.php
    -redolComp.php
    -transbank.php
    -webPay

### Controladores
-No presentaron cambios
    
### Formularios
- No presentaron cambios

### Comandos
- No presentaron cambios.

### Vistas
- No presentaron cambios.

### Repositorios
- No presentaron cambios.

### Eventos
- No presentaron cambios.

### Base de datos
-- No presentaron cambios.

- Procedimientos Almacenados
    - No presentaron cambios.

 - Vistas
    - No presentaron cambios.
